services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/musicdb
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRATION=86400000
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 